AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
    Serverless Application Model implementation.
Parameters:
  ApplicationName:
    Type: String
    Description: Application name
  S3BucketName:
    Type: String
    Description: Name of S3 bucket to hold website content.
  S3SAMBucketName:
    Type: String
    Description: The name of the S3 bucket in which the Swagger specification can be found.
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage
  SourceEmail:
    Type: String
    Default: learntechpuzz@gmail.com
    Description: Source email

Resources:
  # LambdaExecutionRole for lambda functions to allow access Cloud Watch, UserPoolClient, UserPoolDomain, Lambda and DynamoDB 
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ApplicationName}-lambdaexecution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        -
          PolicyName: !Sub ${ApplicationName}-logs-policy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
        -
          PolicyName: !Sub ${ApplicationName}-userpool-policy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action:
                  - 'cognito-idp:CreateUserPoolDomain'
                  - 'cognito-idp:DeleteUserPoolDomain'
                  - 'cognito-idp:DescribeUserPoolDomain'
                  - 'cognito-idp:UpdateUserPoolClient'
                Resource: 'arn:aws:cognito-idp:*:*:userpool/*'
        -
          PolicyName: !Sub ${ApplicationName}-lambda-function-policy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              -
                Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: 'arn:aws:lambda:*:*:function:*'
        -
          PolicyName: !Sub ${ApplicationName}-dynamodb-policy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:BatchGetItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:BatchWriteItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource: 'arn:aws:dynamodb:*:*:table/*'

  # CognitoAuthenticatedRole for cognito-identity to allow access API
  CognitoAuthenticatedRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${ApplicationName}-cognitoauthenticated-role
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Federated: cognito-identity.amazonaws.com
            Action: 
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals: 
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: !Sub ${ApplicationName}-cognito-identity-policy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action:
                  - 'cognito-sync:*'
                  - 'cognito-identity:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'execute-api:Invoke'
                Resource: '*'                

  # Creates a user pool in cognito for your app to auth against
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${ApplicationName}-userpool
      MfaConfiguration: "OFF"
      AutoVerifiedAttributes:
        - email      
      EmailConfiguration: 
        EmailSendingAccount: COGNITO_DEFAULT
        ReplyToEmailAddress: !Sub ${SourceEmail}
        SourceArn: !Sub arn:aws:ses:us-east-1:${AWS::AccountId}:identity/${SourceEmail}
      LambdaConfig:
        PostConfirmation: !GetAtt SaveStudentPostConfirmationFunction.Arn     
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true

  # Creates a User Pool Client to be used by the identity pool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${ApplicationName}-userpoolclient
      GenerateSecret: false
      UserPoolId: !Ref UserPool

  # User Pool Client settings       
  UserPoolClientSettings:
    Type: 'Custom::CognitoUserPoolClientSettings'
    Properties:
      ServiceToken: !GetAtt CognitoUserPoolClientSettings.Arn
      UserPoolId: !Ref UserPool
      UserPoolClientId: !Ref UserPoolClient
      SupportedIdentityProviders:
        - COGNITO
      CallbackURL: !Sub https://s3.amazonaws.com/${S3BucketName}/secured.html 
      LogoutURL: !Sub https://s3.amazonaws.com/${S3BucketName}/public.html 
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - "phone"
        - "email"
        - "openid"        

  # User Pool Domain settings       
  UserPoolDomain:
    Type: 'Custom::CognitoUserPoolDomain'
    Properties:
      ServiceToken: !GetAtt CognitoUserPoolDomain.Arn
      UserPoolId: !Ref UserPool
      Domain: !Sub ${S3BucketName}   

  # Creates a Federeated Identity pool
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub ${ApplicationName}-identitypool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders: 
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # Assigns the roles to the Federeated Identity Pool
  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

  # DynamoDB Students Table
  StudentsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Students"
      AttributeDefinitions: 
        - 
          AttributeName: "UserName"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "UserName"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # DynamoDB Courses Table
  CoursesTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "Courses"
      AttributeDefinitions: 
        - 
          AttributeName: "CourseID"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "CourseID"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  # DynamoDB CourseMaterials Table
  CourseMaterialsTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "CourseMaterials"
      AttributeDefinitions: 
        - 
          AttributeName: "ID"
          AttributeType: "N"
        - 
          AttributeName: "CourseID"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "ID"
          KeyType: "HASH"
        - 
          AttributeName: "CourseID"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  
  # Lambda Function for send response from cognito user pool
  CognitoUserPoolSendResponseFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub ${ApplicationName}-cognitouserpoolsendresponse-function
      Runtime: nodejs8.10
      Code: ./cognito-user-pool-client-domain/CognitoUserPoolSendResponse
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn

  # Lambda Function for setting cognito user pool client
  CognitoUserPoolClientSettingsFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub ${ApplicationName}-cognitouserpoolclientsettings-function
      Runtime: nodejs8.10
      Code: ./cognito-user-pool-client-domain/CognitoUserPoolClientSettings.js
      Handler: CognitoUserPoolClientSettings.handler
      Role: !GetAtt LambdaExecutionRole.Arn
    DependsOn: CognitoUserPoolSendResponseFunction    

  # Lambda Function for setting cognito user pool domain
  CognitoUserPoolDomainFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub ${ApplicationName}-cognitouserpooldomain-function
      Runtime: nodejs8.10
      Code: ./cognito-user-pool-client-domain/CognitoUserPoolDomain.js
      Handler: CognitoUserPoolDomain.handler
      Role: !GetAtt LambdaExecutionRole.Arn
    DependsOn: CognitoUserPoolSendResponseFunction

  # Lambda Function to add student into Dynamo DB (PostConfirmation trigger from Cognito)    
  CreateStudentPostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-createstudentpostconfirmation-function
      Runtime: java8
      Timeout: 300
      MemorySize: 512
      Handler: com.learntechpuzz.lambda.function.StudentFunctions::createStudent
      CodeUri: ./learntechpuzz-lambda-functions/target/learntechpuzz-lambda-functions-1.0.0.jar
      Role: !GetAtt LambdaExecutionRole.Arn

